project:
  type: website
  output-dir: docs

website:
  favicon: "img/R.svg"
  title: "Stat ClubR"
  search: 
    location: navbar
    type: overlay
  navbar:
    title: "*Stat Club***R** "
    background: "#44bce1"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/upulcooray
      - icon: google
        href: https://scholar.google.com/citations?user=VcgfAmoAAAAJ&hl=en
format:
  html:
    theme:
      light: cosmo
      dark: solar
    fontsize: 1.5em
    page-layout: full
    css: styles.css

editor: visual

