project:
  type: website

website:
  title: "Stat ClubR"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: google
        href: https://scholar.google.com/citations?user=VcgfAmoAAAAJ&hl=en
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

